In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("D:\Customer-ProjectData.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14.0,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2.0,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23.0,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49.0,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31.0,PayPal,Annually

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3899 non-null   object
 3   Item Purchased          3899 non-null   object
 4   Category                3899 non-null   object
 5   Purchase Amount (USD)   3898 non-null   float64
 6   Location                3897 non-null   object
 7   Size                    3899 non-null   object
 8   Color                   3899 non-null   object
 9   Season                  3898 non-null   object
 10  Review Rating           3862 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3899 non-null   object
 13  Discount Applied        3899 non-null   object
 14  Promo Code Used         3898 non-null   object
 15  Previous Purchases      3899 non-null   float64
 16  Payment Method          3898 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(3), int64(2), object(13)
memory usage: 548.6+ KB

In [26]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     1
Item Purchased             1
Category                   1
Purchase Amount (USD)      2
Location                   3
Size                       1
Color                      1
Season                     2
Review Rating             38
Subscription Status        0
Shipping Type              1
Discount Applied           1
Promo Code Used            2
Previous Purchases         1
Payment Method             2
Frequency of Purchases     0
dtype: int64

In [8]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [9]:
for col in df.select_dtypes(include=['int64','float64']).columns:
    df[col] = df[col].fillna(df[col].median())

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [31]:
df.columns = [
    'customer_id',
    'age',
    'gender',
    'item_purchased',
    'category',
    'purchase_amount_usd',
    'location',
    'size',
    'color',
    'season',
    'review_rating',
    'subscription_status',
    'shipping_type',
    'discount_applied',
    'promo_code_used',
    'previous_purchases',
    'payment_method',
    'frequency_of_purchases'
]

In [12]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [33]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14.0,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2.0,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23.0,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49.0,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31.0,PayPal,Annually

In [34]:
df.tail()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
3895,3896,40,Female,Hoodie,Clothing,28.0,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32.0,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49.0,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41.0,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33.0,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24.0,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77.0,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24.0,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81.0,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33.0,Venmo,Quarterly

In [35]:
df.describe()

,customer_id,age,purchase_amount_usd,review_rating,previous_purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.768462,3.750333,25.346923
std,1125.977353,15.207589,23.676844,0.713460,14.444361
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [36]:
df.to_csv("eda_customer_data.csv", index=False)
df

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14.0,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2.0,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23.0,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49.0,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31.0,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28.0,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32.0,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49.0,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41.0,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33.0,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24.0,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77.0,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24.0,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81.0,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33.0,Venmo,Quarterly

In [15]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64